#!/usr/bin/env bash
# Smoke test the konrad image. Runs in CI before publishing to the
# registry — if any check fails, the daily build does not move the
# `:latest` tag and last-known-good keeps serving users. Also runnable
# locally:
#
#   ./scripts/smoke-test.sh                # tests konrad:latest
#   ./scripts/smoke-test.sh my-tag:1.2     # tests an arbitrary tag
#
# The checks are deliberately "installed and importable" rather than
# "agent runs end-to-end" — exercising opencode requires a model
# provider, which is user-specific. Catching basic install regressions is
# what makes the float-everything pinning strategy safe.
set -euo pipefail

IMAGE="${1:-konrad:latest}"

# --- Output helpers ---
pass() { printf '  \033[32mPASS\033[0m  %s\n' "$*"; }
fail() { printf '  \033[31mFAIL\033[0m  %s\n' "$*" >&2; exit 1; }
info() { printf '\n\033[1m%s\033[0m\n' "$*"; }

# Run a one-shot command inside the image, no workspace mount needed.
in_image() { podman run --rm --entrypoint "" "$IMAGE" "$@"; }

info "smoke-testing $IMAGE"

# --- 1. Image exists ---
podman image exists "$IMAGE" \
  || fail "image $IMAGE not found locally — build it first"
pass "image present"

# --- 2. Core binaries on PATH ---
info "core binaries"
for bin in opencode node npm python3 uv typst jq git ripgrep fd bat gh; do
  in_image which "$bin" >/dev/null \
    || fail "$bin not on PATH"
  pass "$bin"
done

# --- 3. Tool versions print (catches broken installs) ---
info "version probes"
in_image node    --version >/dev/null || fail "node --version failed"
in_image npm     --version >/dev/null || fail "npm --version failed"
in_image python3 --version >/dev/null || fail "python3 --version failed"
in_image uv      --version >/dev/null || fail "uv --version failed"
in_image typst   --version >/dev/null || fail "typst --version failed"
in_image opencode --version >/dev/null || fail "opencode --version failed"
pass "all version probes returned 0"

# --- 4. Python skill deps import ---
info "python skill imports"
in_image python3 -c '
import docling          # EXTRACT route
import pypdf            # EDIT route
import pdfplumber       # region discovery
import pdf2image        # rasterization
import reportlab        # GENERATE route
import openpyxl, pandas # spreadsheets skill
import onnxruntime      # rapidocr engine
print("ok")
' >/dev/null || fail "python skill imports failed"
pass "docling, pypdf, pdfplumber, pdf2image, reportlab, openpyxl, pandas, onnxruntime"

# --- 5. Build manifest exists and parses ---
info "build manifest"
in_image test -f /etc/konrad/build-manifest.json \
  || fail "/etc/konrad/build-manifest.json missing"
in_image jq -e '.konrad.version, .konrad.build_date, .tooling.node, .apt[0], .python[0]' \
  /etc/konrad/build-manifest.json >/dev/null \
  || fail "manifest JSON missing expected keys"
KONRAD_VER=$(in_image jq -r .konrad.version /etc/konrad/build-manifest.json)
BUILD_DATE=$(in_image jq -r .konrad.build_date /etc/konrad/build-manifest.json)
pass "manifest valid (konrad=$KONRAD_VER, built=$BUILD_DATE)"

# --- 6. Bundled config files in place ---
info "baked content"
in_image test -f /etc/konrad/opencode-defaults.jsonc \
  || fail "opencode-defaults.jsonc missing"
in_image test -f /etc/konrad/instructions.md \
  || fail "instructions.md missing"
in_image test -d /home/node/.config/opencode/skills/pdf \
  || fail "pdf skill missing"
in_image test -d /home/node/.config/opencode/skills/quality-assurance \
  || fail "quality-assurance skill missing"
in_image test -d /usr/local/share/fonts/konrad \
  || fail "bundled fonts missing"
pass "konrad defaults, skills, and fonts present"

# --- 7. End-to-end: docling extracts a tiny PDF ---
# Catches regressions in the docling/onnxruntime/rapidocr chain that
# version probes alone won't detect.
info "docling end-to-end"
in_image bash -c '
set -e
cd /tmp
# Minimal 1-page PDF with the text "smoke" — generated by reportlab so
# we do not depend on having a test fixture in the image.
python3 -c "
from reportlab.pdfgen import canvas
c = canvas.Canvas(\"/tmp/smoke.pdf\")
c.drawString(100, 750, \"smoke\")
c.save()
"
docling /tmp/smoke.pdf --to md --output /tmp/out >/dev/null
grep -qi smoke /tmp/out/smoke.md
' || fail "docling round-trip failed"
pass "docling extracted a generated PDF"

# --- All clear ---
printf '\n\033[32mall checks passed for %s\033[0m\n' "$IMAGE"
